#ifndef SUDOKUERRORS_H
#define SUDOKUERRORS_H

typedef enum
{
	SUDOKU_SUCCESS,
	SUDOKU_ERROR_OPEN_FILE,
	SUDOKU_ERROR_INVALID_DATA,
	SUDOKU_ERROR_INCORRECT_BOARD
} SUDOKU_Errors;

#endif	  // SUDOKUERRORS_H
